spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: site.leui.todoserver.domain


